using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Remold.Core;
using Remold.Core.Migoto;
using Xunit;

namespace Remold.Core.Tests.Migoto;

public class BuildWatermarkTests
{
    internal const string MarkerPrefix = "; generated override set ";

    [Fact]
    public void Core_short_hash_identifies_the_loaded_Core_binary()
    {
        using var stream = File.OpenRead(typeof(ModBuilder).Assembly.Location);
        string expected = Convert.ToHexString(SHA256.HashData(stream).AsSpan(0, 6)).ToLowerInvariant();

        Assert.Equal(expected, CoreBuildIdentity.ShortHash);
    }

    [Fact]
    public void Marker_follows_both_emitter_headers_when_a_build_has_pooled_and_rigid_routes()
    {
        string root = Path.Combine(Path.GetTempPath(), "remold-watermark-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        try
        {
            File.WriteAllText(Path.Combine(root, "mod.ini"),
                MigotoEmitter.PooledIniHeader + "\n" + MigotoEmitter.RigidIniHeader + "\n[Present]\n");

            ModBuilder.StampCoreBuild(root);

            string ini = File.ReadAllText(Path.Combine(root, "mod.ini")).Replace("\r\n", "\n");
            string expectedPrefix = MigotoEmitter.PooledIniHeader + "\n" + MigotoEmitter.RigidIniHeader
                + MarkerPrefix + CoreBuildIdentity.ShortHash + "\n\n";
            Assert.StartsWith(expectedPrefix, ini, StringComparison.Ordinal);
        }
        finally { try { Directory.Delete(root, recursive: true); } catch { } }
    }

    [Fact]
    public void Missing_emitter_header_seam_is_refused_by_name()
    {
        string root = Path.Combine(Path.GetTempPath(), "remold-watermark-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        try
        {
            File.WriteAllText(Path.Combine(root, "mod.ini"), MigotoEmitter.RigidIniHeader + "[Present]\n",
                new UTF8Encoding(false));

            var error = Assert.Throws<InvalidOperationException>(() => ModBuilder.StampCoreBuild(root));

            Assert.Equal("the emitted mod.ini carries no generated comment header seam to place the Core build marker",
                error.Message);
        }
        finally { try { Directory.Delete(root, recursive: true); } catch { } }
    }

    internal static void AssertStamped(ModBuilder.Result result, bool expectRepair = true)
    {
        string expected = MarkerPrefix + CoreBuildIdentity.ShortHash;
        string ini = File.ReadAllText(Path.Combine(result.OutDir, "mod.ini"));
        AssertOneMarker(ini, expected);

        string gf2mod = Path.Combine(result.OutDir, "gf2mod.json");
        Assert.True(File.Exists(gf2mod), "expected build sidecar 'gf2mod.json'");
        Assert.DoesNotContain(CoreBuildIdentity.ShortHash, File.ReadAllText(gf2mod), StringComparison.Ordinal);
        string repair = Path.Combine(result.OutDir, "repair.json");
        Assert.Equal(expectRepair, File.Exists(repair));
        if (expectRepair)
        {
            Assert.DoesNotContain(CoreBuildIdentity.ShortHash, File.ReadAllText(repair), StringComparison.Ordinal);
        }

        Assert.NotNull(result.ZipPath);
        using var zip = ZipFile.OpenRead(result.ZipPath!);
        var zippedIni = Assert.Single(zip.Entries, entry => entry.Name == "mod.ini");
        using (var reader = new StreamReader(zippedIni.Open()))
            AssertOneMarker(reader.ReadToEnd(), expected);

        var zippedGf2mod = Assert.Single(zip.Entries, candidate => candidate.Name == "gf2mod.json");
        using (var reader = new StreamReader(zippedGf2mod.Open()))
            Assert.DoesNotContain(CoreBuildIdentity.ShortHash, reader.ReadToEnd(), StringComparison.Ordinal);
        var zippedRepair = zip.Entries.Where(candidate => candidate.Name == "repair.json").ToList();
        Assert.Equal(expectRepair ? 1 : 0, zippedRepair.Count);
        if (expectRepair)
        {
            using var reader = new StreamReader(zippedRepair[0].Open());
            Assert.DoesNotContain(CoreBuildIdentity.ShortHash, reader.ReadToEnd(), StringComparison.Ordinal);
        }
    }

    private static void AssertOneMarker(string ini, string expected)
    {
        string normalized = ini.Replace("\r\n", "\n", StringComparison.Ordinal);
        var marker = Assert.Single(Regex.Matches(normalized,
            @"(?m)^; generated override set [0-9a-f]{12}$").Cast<Match>());
        Assert.Equal(expected, marker.Value);
        Assert.DoesNotContain("; drl ", normalized, StringComparison.Ordinal);

        Assert.Matches(@"\A; .+ - generated by the Remold .+ emitter\n", normalized);
        int headerEnd = normalized.IndexOf("\n\n", StringComparison.Ordinal);
        Assert.Equal(marker.Index + marker.Length, headerEnd);
        Assert.False(normalized.TrimEnd('\n').EndsWith(expected, StringComparison.Ordinal),
            "the Core marker must be embedded in the generated body, not appended at the file end");
    }
}
